image: registry.gitlab.com/pages/hugo:latest

variables:
  HUGO_VERSION: 0.119.0  # Use the latest version

pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - main  # Adjust the branch as needed
